### ISSUE TITLE
Quests - picking item keeps saying Quest Completed

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#107]
When you've reached the quest target (5 turtle shells for example), each item you pick up for the quest afterward also says that you've finished the quest, again.
So when you pick the 6th turtle shell, even though the quest needs 5, it again says that you've finished the quest, and so on.

**Comment by Tzook** [comment]
@benk0913 I saw this happening again today.

**Comment by benk0913** [comment]
@Tzook 
For the 6th? or for redropping the 5th?

**Comment by Tzook** [comment]
For picking any item after the 5th (6th, 7th and so on)
