### ISSUE TITLE
Create Character - separate hair/eyes colors from styles

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#110]
Even though it is stored as one, we should enable the user to select them as if they were two different things.
So you can first choose the hair style and then select the hair color. Same with eyes. 
The actual result is the same sprite that we already have and use.

**Comment by benk0913** [comment]
The ratio of work to "revenue of feature" here is bad. Quite a hassle, would make future hair "addings" problematic and could lead to more bugs while scaling the variety. (Oops the brown hair fell on the blonde hair accidently etc...)
This isn't critical, I have already seen a few games doing it like we did.
Not so bad, for now. 
Could be implemented after alpha / polish phase...
