### ISSUE TITLE
Show "right-click" indication on NPC with the first NPC

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#113]
The game begins with an NPC, but you don't know how to chat with him.
Need to do one of the following:
* remove the NPC - there are many more in other areas.
* move the "right-click to talk to NPC" hint to be at the beginning.

**Comment by benk0913** [comment]
This NPC is not essential to the progress of the game, and there more for a funny joke purpose.
He is a some sort of a wink for experienced players.
