### ISSUE TITLE
Mini log - center on screen

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#123]
It's hard to notice the log. 
It would be more visible if it were at the center of the screen (like quests progress are, but this is smaller since it appears more often)

**Comment by benk0913** [comment]
First priority is to prevent cognitive mess, then the another priority is to prevent UI from hiding too much of the screen (See where it failed: https://www.blogcdn.com/wow.joystiq.com/media/2009/09/ui.jpg )
Putting text in the center of the screen would make some mess and take the focus off the world.
