### ISSUE TITLE
Character entering map - slides in

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#125]
When a character enters the map (from a portal for example), his position is sliding in.
It should appear on the spot instead.

**Comment by benk0913** [comment]
This might be problematic, since the character "spawns" in a fixed place and then moved to the correct pos which is based on "Actor Moved" events... @Tzook

**Comment by Tzook** [comment]
Maybe we should say that if the character travels more than x distance, it just teleports instantly and doesn't slide in.

**Comment by Tzook** [comment]
Might be related to #152.
