### ISSUE TITLE
Background goes over item info sometimes

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#146]
<img width="1680" alt="screen shot 2017-07-12 at 1 06 19" src="https://user-images.githubusercontent.com/7537694/28501415-25569516-6fe4-11e7-85c3-8191a84774f7.png">

**Comment by benk0913** [comment]
Cant see screenshot... Which background? @Tzook

**Comment by Tzook** [comment]
@benk0913 updated the image.

**Comment by benk0913** [comment]
@Tzook  Can't see anything wrong in the picture...

**Comment by Tzook** [comment]
@benk0913 Look at the arrow after the minimum level, the tree behind is a bit above it.

**Comment by benk0913** [comment]
fixed
