### ISSUE TITLE
Interrupt when starting to charge keeps the charging UI.

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#150]
If you begin charging and attack and right then you get hit quickly, the charging UI will get stuck.

**Comment by benk0913** [comment]
This does not happen.. /=

**Comment by Tzook** [comment]
See the following GIF, as I begin attacking slightly before the moment that I get interrupted:
![ezgif-3-5ef2ada58e](https://user-images.githubusercontent.com/7537694/28501568-2774bd3e-6fe7-11e7-8040-4eed0a0fffd6.gif)

**Comment by benk0913** [comment]
Managed to fix it, tell me if you spot this again, I might have had trouble reproducing it instead...
