### ISSUE TITLE
Attacking with a weapon on a rope and disconnecting and reconnecting will make you use that weapon as a bow

### ISSUE THREAD

**Issue by hagixxg28** [Tzook/lel#154]
There is the known bug that if you hold fire and go on a ladder you can start shooting from ladders.
If you go one step further and hold an attack and disconnect, your attack type will be switched to shoot when you log back in even if you can't use that weapon as a bow.

**Comment by Tzook** [comment]
wow! nice bug!!!

**Comment by benk0913** [comment]
Cant reproduce @Tzook  @hagixxg28
