### ISSUE TITLE
Abandon Quest

### ISSUE THREAD

**Issue by benk0913** [Tzook/lel#163]
The ability to abandon a quest, this removes the quest by given quest key and all of the quest items which belong to that quest. 

@Tzook

**Comment by Tzook** [comment]
@benk0913 this is already supported in the server. Check out the jaxdox:
https://docs.google.com/document/d/1nR84J6jPV4iiTIRH5bDUEQfZSU7oQMxTxyOKGgmBv5w/edit#bookmark=kix.uy9bnbswow6s
