### ISSUE TITLE
End NPC for quests

### ISSUE THREAD

**Issue by benk0913** [Tzook/lel#164]
Quests should now have an "ending NPC" which would be set to the NPC which gives the reward for the quest.

**Comment by Tzook** [comment]
This is now available. @benk0913 .
Now just need to make sure that all quests have a giving NPC and have an ending NPC.

I've also added the following to the client: 
* Sending the giving / ending quests of an NPC to the content god
* Sending NPC key when starting / ending a quest, so it can be validated in the server.
