### ISSUE TITLE
Spell that doesn't hit a mob doesn't tell the server that it happened

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#212]
we might need to split it into 2 events:
1 - spell activated. this just reduces the mana and shows other clients the spell.
2 - spell hit mob. this actually hurts any mobs the collider meets.
it's a bit problematic because we can't verify that the user does event 2 right after event 1, so event 2 can be spammed by hackers easily. I'm open to suggestions.

option b - we send the use spell event after the collider hits. if it doesn't hit anything, we send it with no mobs.

**Comment by benk0913** [comment]
@Tzook  What do you say? I prefer solution 1
