### ISSUE TITLE
[Items] Dragging an item sometimes displays behind the background

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#241]
Try to go to GrassLands4 and drag an item like the following image:

<img width="1680" alt="screen shot 2018-03-05 at 16 02 40" src="https://user-images.githubusercontent.com/7537694/36978902-6cb45c8a-208e-11e8-94bc-07c1571d3104.png">

(The glove is behind the bushes)

**Comment by benk0913** [comment]
cant reproduce
