### ISSUE TITLE
[Bug] When destorying an actor (when h... (by becker)

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#302]
User's description:
When destorying an actor (when he leaves a room), it destroys all its children. If the actor was hurt just before, the "PopHint" (and probably other children too) are also destroyed. Then, it cannot be recycled in the resources

**Comment by benk0913** [comment]
@Tzook  is this crutual?

**Comment by Tzook** [comment]
Yes, this is very important.
The result is that any time you should hit the mob it throws an error instead and it looks super buggy. 
I can reproduce this easily.
