### ISSUE TITLE
Melee attack - should hit the closest mob to you

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#350]
This is happening with melee, especially with 2 handed weapons. 
Hits are supposed to send the closest mob as the first mob in the hurt mobs list event.

@benk0913 do you think it should be calculated on the server? it's possible, the info is there.

**Comment by benk0913** [comment]
Hell no, this shit shouldn't be calculated on the server.
For now its not sooo bad, sometimes its even more intuitive, for example when you use a two handed hammer / axe , you expect the tip to be the most and first active.

**Comment by Tzook** [comment]
Closing - not important enough
