### ISSUE TITLE
If you throw alot of money, the red sprite will be clearly shown

### ISSUE THREAD

**Issue by hagixxg28** [Tzook/lel#48]
![image](https://cloud.githubusercontent.com/assets/28218548/25578260/89b7767a-2e75-11e7-8f9d-f0262ce6f676.png)
.

Just remove the red sprite from the money, it's not noticeable anyway if there is  a small amout of money.

also, lots of money crash the server. I guess it's not a biggy beucase the host is not crazy yet

**Comment by Tzook** [comment]
@hagixxg28 I tried to reproduce that. I dropped a lot of money and the server didn't crash. Maybe it was caused by something else.

**Comment by Tzook** [comment]
Closing this. Duplicate of https://github.com/Tzook/lul/issues/30
