### ISSUE TITLE
Milestone Meeting

### ISSUE THREAD

**Issue by benk0913** [Tzook/lel#64]
**Questions to discuss:**

1) What should be done with the spam of items? 
2) Talk about starting items.
3) Remove starter maps?
4) How classes will work (How to get class / what it provides )
5) How ranged primary ability will work
6) How sub spells will work
7) Talent window 
8) Discuss DEX again
9) How arrows consumption will work
10) How do I bind sub spells

**Things to do in this milestone:**

Additional 2 grass maps
Create jungle theme
3 Class NPCS
Classes

@Tzook

**Comment by Tzook** [comment]
We should probably do quests before we begin classes.
In my opinion, getting a class (to be discussed) will be in form of a quest.

**Comment by benk0913** [comment]
I agree

**Comment by Tzook** [comment]
Discussion summary:
1. Dropping gold will be limited to one per second (server)
2. Content god sends list of equip-keys to wear at the beginning
3. OK (server)

* Don't send entire character data to other players (server)
* Content god - sends NPCs for each map

Quests:
* Add quest in progress & available quest conditions to dialog bubbles (client)
* Structure: key, name, in progress description, done description, complete condition list (condition, type, currentValue, completeValue), requirements (quests keys completed list, lvl, class), rewards (exp, items (key, stack)), starterNPC, finisherNPC
* Make sure has inventory slots available for rewards
* NPCs available / progress / complete visual hints

4.
