### ISSUE TITLE
Add quests to CONTENT GOD

### ISSUE THREAD

**Issue by benk0913** [Tzook/lel#68]
https://github.com/Tzook/lel/issues/64 

for more info

**Comment by benk0913** [comment]
@Tzook 

Added quests to Content god

This is the following json construction code:
`
        node["pass"] = "b0ss123";

        for (int i = 0; i < Quests.Count; i++)
        {
            node["items"][i]["key"] = Quests[i].Key;
            node["items"][i]["name"] = Quests[i].Name;

            for( int c=0 ; c < Quests[i].Conditions.Count ; c++ )
            {
                node["items"][i]["conditions"][c]["condition"] = Quests[i].Conditions[c].Condition;
                node["items"][i]["conditions"][c]["conditionType"] = Quests[i].Conditions[c].Type;
                node["items"][i]["conditions"][c]["targetProgress"] = Quests[i].Conditions[c].TargetProgress.ToString();
            }

            for (int rc = 0; rc < Quests[i].RequiredCompletedQuests.Count; rc++)
            {
                node["items"][i]["RequiredQuests"][rc]["key"] = Quests[i].RequiredCompletedQuests[rc];
            }

            node["items"][i]["requiredClass"] = Quests[i].RequiredClass;

            node["items"][i]["minLevel"] = Quests[i].MinimumLevel.ToString();


            for (int ri = 0; ri < Quests[i].RewardItems.Count; ri++)
            {
                node["items"][i]["rewardItems"][ri]["key"] = Quests[i].RewardItems[ri].ItemKey;
                node["items"][i]["rewardItems"][ri]["stack"] = Quests[i].RewardItems[ri].MinStack.ToString();
            }

            node["items"][i]["rewardClass"] = Quests[i].RewardClass.ToString();

        }`

it is supposed to be sent to /quests

**Comment by Tzook** [comment]
@benk0913 Boss, what about rewards ability and stats?

**Comment by benk0913** [comment]
Added an additional issue that includes those two, must add them after we implemented the 'Ranged' ability and the classes are figured out. Lets first finish the current tasks then continue to those @Tzook

**Comment by Tzook** [comment]
What about starting / finishing NPC? We need to talk about that.
